# Example compose file...currently does not work.

elasticsearch:
  build: elasticsearch
  working_dir: /data
  command: /elasticsearch/bin/elasticsearch -Des.config=/data/config/elasticsearch.yml
  volumes:
    - /var/lib/docker/npmsearch/elasticsearch/data:/data
    - ./elasticsearch/config:/data/config
  ports:
    - "9200:9200"
    - "9300:9300"